# Generated by Django 5.2.7 on 2025-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlclient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
