# Generated by Django 5.2.7 on 2025-11-06 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContactsCreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ghl_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location_id', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('title', models.CharField(default='Cita', max_length=200)),
                ('appointment_status', models.CharField(default='confirmed', max_length=50)),
                ('assigned_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='ContactsCreate.contact')),
            ],
        ),
    ]
