# Generated by Django 5.2.7 on 2025-11-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentCreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='calendar_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, default='Cita', max_length=200, null=True),
        ),
    ]
