# Generated by Django 5.2.7 on 2025-11-07 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentpreference_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpreference',
            name='description',
        ),
    ]
